"""add notification preferences and deadline alert log

Revision ID: 3070be424227
Revises: 857d8c12c3f6
Create Date: 2026-07-30 07:38:16.152835
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.db import rls_statements

revision: str = '3070be424227'
down_revision: str | None = '857d8c12c3f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadline_alert_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('deadline_id', sa.Uuid(), nullable=False),
    sa.Column('alert_day', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'deadline_id', 'alert_day')
    )
    op.create_index(op.f('ix_deadline_alert_log_deadline_id'), 'deadline_alert_log', ['deadline_id'], unique=False)
    op.create_index(op.f('ix_deadline_alert_log_opportunity_id'), 'deadline_alert_log', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_deadline_alert_log_user_id'), 'deadline_alert_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_deadline_alert_log_workspace_id'), 'deadline_alert_log', ['workspace_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email_deadlines', sa.Boolean(), nullable=False),
    sa.Column('sms_deadlines', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.Integer(), nullable=True),
    sa.Column('quiet_hours_end', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )

    if op.get_bind().dialect.name == "postgresql":
        for stmt in rls_statements("deadline_alert_log"):
            op.execute(stmt)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_deadline_alert_log_workspace_id'), table_name='deadline_alert_log')
    op.drop_index(op.f('ix_deadline_alert_log_user_id'), table_name='deadline_alert_log')
    op.drop_index(op.f('ix_deadline_alert_log_opportunity_id'), table_name='deadline_alert_log')
    op.drop_index(op.f('ix_deadline_alert_log_deadline_id'), table_name='deadline_alert_log')
    op.drop_table('deadline_alert_log')
    # ### end Alembic commands ###
