"""add mfa otp columns

Revision ID: 45018dce267d
Revises: 64f9e4b70eda
Create Date: 2026-07-29 12:06:34.853906
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '45018dce267d'
down_revision: str | None = '64f9e4b70eda'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mfa_otp_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('mfa_otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_otp_expires_at')
    op.drop_column('users', 'mfa_otp_code')
    # ### end Alembic commands ###
