"""Add award_documents and mfa_otp columns

Revision ID: 5a5548916ff0
Revises: 45018dce267d
Create Date: 2026-07-29 12:20:57.272060
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.db import rls_statements

revision: str = '5a5548916ff0'
down_revision: str | None = '45018dce267d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('award_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_award_documents_opportunity_id'), 'award_documents', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_award_documents_workspace_id'), 'award_documents', ['workspace_id'], unique=False)

    # Apply workspace-isolation RLS to this newly created table (PostgreSQL only).
    if op.get_bind().dialect.name == "postgresql":
        for stmt in rls_statements("award_documents"):
            op.execute(stmt)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_award_documents_workspace_id'), table_name='award_documents')
    op.drop_index(op.f('ix_award_documents_opportunity_id'), table_name='award_documents')
    op.drop_table('award_documents')
    # ### end Alembic commands ###
