"""TS-163 account-centric auth schema

Revision ID: 6cffa6139050
Revises: 3e8f87662b2f
Create Date: 2026-07-30 05:29:16.266352
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6cffa6139050'
down_revision: str | None = '3e8f87662b2f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobile_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_mobile_verifications_user_id'), 'mobile_verifications', ['user_id'], unique=False)
    op.add_column('users', sa.Column('org_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=False))
    op.add_column('users', sa.Column('mobile_verified', sa.Boolean(), nullable=False))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'apple_id')
    op.drop_column('users', 'google_sub')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_sub', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('apple_id', sa.VARCHAR(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'mobile_verified')
    op.drop_column('users', 'city')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'org_name')
    op.drop_index(op.f('ix_mobile_verifications_user_id'), table_name='mobile_verifications')
    op.drop_table('mobile_verifications')
    # ### end Alembic commands ###
