"""notification preferences columns and api

Revision ID: c91c4ce7e733
Revises: f94c5d977344
Create Date: 2026-07-30 11:50:34.349734
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c91c4ce7e733'
down_revision: str | None = 'f94c5d977344'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'notification_preferences',
        sa.Column('email_digest', sa.Boolean(), nullable=False, server_default=sa.true())
    )
    op.add_column(
        'notification_preferences',
        sa.Column('sms_alerts', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column(
        'notification_preferences',
        sa.Column('marketing', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'marketing')
    op.drop_column('notification_preferences', 'sms_alerts')
    op.drop_column('notification_preferences', 'email_digest')
    # ### end Alembic commands ###
