"""add user pending email columns

Revision ID: e0b624d27501
Revises: c91c4ce7e733
Create Date: 2026-07-30 12:04:54.943101
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e0b624d27501'
down_revision: str | None = 'c91c4ce7e733'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('pending_email_token_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pending_email_token_hash')
    op.drop_column('users', 'pending_email')
    # ### end Alembic commands ###
