"""add admin billing support analytics

Revision ID: f94c5d977344
Revises: f5c03761fb0c
Create Date: 2026-07-30 09:56:32.675688
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f94c5d977344'
down_revision: str | None = 'f5c03761fb0c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_workspace_id'), 'support_tickets', ['workspace_id'], unique=False)
    op.create_table('support_ticket_replies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_ticket_replies_ticket_id'), 'support_ticket_replies', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_support_ticket_replies_user_id'), 'support_ticket_replies', ['user_id'], unique=False)
    op.create_index(op.f('ix_support_ticket_replies_workspace_id'), 'support_ticket_replies', ['workspace_id'], unique=False)
    op.create_table('support_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=True),
    sa.Column('reply_id', sa.Uuid(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['reply_id'], ['support_ticket_replies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_attachments_reply_id'), 'support_attachments', ['reply_id'], unique=False)
    op.create_index(op.f('ix_support_attachments_ticket_id'), 'support_attachments', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_support_attachments_workspace_id'), 'support_attachments', ['workspace_id'], unique=False)
    op.add_column('users', sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('suspended_by', sa.Uuid(), nullable=True))
    op.add_column('workspaces', sa.Column('billing_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'billing_settings')
    op.drop_column('users', 'suspended_by')
    op.drop_column('users', 'suspended_at')
    op.drop_index(op.f('ix_support_attachments_workspace_id'), table_name='support_attachments')
    op.drop_index(op.f('ix_support_attachments_ticket_id'), table_name='support_attachments')
    op.drop_index(op.f('ix_support_attachments_reply_id'), table_name='support_attachments')
    op.drop_table('support_attachments')
    op.drop_index(op.f('ix_support_ticket_replies_workspace_id'), table_name='support_ticket_replies')
    op.drop_index(op.f('ix_support_ticket_replies_user_id'), table_name='support_ticket_replies')
    op.drop_index(op.f('ix_support_ticket_replies_ticket_id'), table_name='support_ticket_replies')
    op.drop_table('support_ticket_replies')
    op.drop_index(op.f('ix_support_tickets_workspace_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    # ### end Alembic commands ###
